version: '3'

services:
    fastapi:
        container_name: fastapi
        build: "."
        volumes:
          - .:/usr/src/app
        ports:
          - "5000:5000"
        command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
